import { useCallback, useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import AdminLayout from "../../../layouts/AdminLayout";
import { useToast } from "../students/components/Toast";
import { getAcademicSections } from "../academic/academic.service";
import { getTeachers } from "../teachers/services/teacher.service";
import { assignSubjectTeacher, getSubject, getSubjectTeachers, unassignSubjectTeacher } from "./subject.service";
import type { Subject, TeacherAssignment } from "./subject.types";

export default function SubjectDetailPage() {
  const { id } = useParams(); const subjectId = Number(id); const navigate = useNavigate(); const { showToast } = useToast();
  const [subject, setSubject] = useState<Subject>(); const [assignments, setAssignments] = useState<TeacherAssignment[]>([]); const [teachers, setTeachers] = useState<{ id: number; fullName: string }[]>([]); const [sections, setSections] = useState<{ id: number; name: string }[]>([]); const [teacherId, setTeacherId] = useState(0); const [sectionId, setSectionId] = useState(0);
  const load = useCallback(async () => { const item = await getSubject(subjectId); setSubject(item); const [assigned, teacherPage, sectionPage] = await Promise.all([getSubjectTeachers(subjectId), getTeachers(1, 100), getAcademicSections(item.classId, 0, 100)]); setAssignments(assigned); setTeachers(teacherPage.data.map((value) => ({ id: value.id, fullName: `${value.firstName} ${value.lastName}`.trim() }))); setSections(sectionPage.content); }, [subjectId]);
  useEffect(() => { queueMicrotask(() => load().catch(() => showToast("Failed to load subject", "error"))); }, [load, showToast]);
  if (!subject) return <AdminLayout><div className="p-8">Loading subject...</div></AdminLayout>;
  const assign = async () => { if (!teacherId || !sectionId) { showToast("Select teacher and section", "error"); return; } try { await assignSubjectTeacher(subjectId, { teacherId, sectionId }); showToast("Teacher assigned successfully", "success"); await load(); } catch (error) { showToast((error as { response?: { data?: { message?: string } } }).response?.data?.message || "Assignment failed", "error"); } };
  const teacherName = (teacher: number) => teachers.find((item) => item.id === teacher)?.fullName || `Teacher ${teacher}`; const sectionName = (section: number) => sections.find((item) => item.id === section)?.name || `Section ${section}`;
  return <AdminLayout><div className="space-y-6"><div className="flex flex-col sm:flex-row sm:justify-between gap-3"><div><h1 className="text-2xl md:text-3xl font-bold">{subject.subjectName}</h1><p className="text-gray-500">{subject.subjectCode} · {subject.className}</p></div><button onClick={() => navigate(`/admin/subjects/${subject.id}/edit`)} className="px-5 py-2 rounded-xl bg-[#234A91] text-white">Edit Subject</button></div><div className="grid grid-cols-2 md:grid-cols-4 gap-4">{[["Type",subject.subjectType],["Marks",`${subject.passMarks} / ${subject.fullMarks}`],["Credit Hours",subject.creditHours],["Requirement",subject.optional ? "Optional" : "Compulsory"],["Status",subject.status],["Teachers",subject.assignedTeacherCount],["Created",subject.createdAt],["Updated",subject.updatedAt]].map(([label,value]) => <div key={String(label)} className="bg-white rounded-xl p-4 shadow-sm"><p className="text-xs text-gray-500 uppercase">{label}</p><p className="mt-1 font-medium">{String(value)}</p></div>)}</div><div className="bg-white rounded-xl p-5 shadow-sm"><h2 className="font-semibold mb-4">Teacher Assignments</h2><div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mb-4"><select value={teacherId || ""} onChange={(event) => setTeacherId(Number(event.target.value))} className="h-10 border rounded-xl px-3"><option value="">Select Teacher</option>{teachers.map((item) => <option key={item.id} value={item.id}>{item.fullName}</option>)}</select><select value={sectionId || ""} onChange={(event) => setSectionId(Number(event.target.value))} className="h-10 border rounded-xl px-3"><option value="">Select Section</option>{sections.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button onClick={assign} className="h-10 rounded-xl bg-[#234A91] text-white">Assign Teacher</button></div><div className="space-y-2">{assignments.map((item) => <div key={item.id} className="flex justify-between border rounded-xl p-3"><span>{teacherName(item.teacherId)} · Section {sectionName(item.sectionId)}</span><button onClick={async () => { await unassignSubjectTeacher(subjectId, item.teacherId); showToast("Teacher unassigned", "success"); await load(); }} className="text-red-600">Remove</button></div>)}{assignments.length === 0 && <p className="text-gray-500">No teachers assigned.</p>}</div></div></div></AdminLayout>;
}
