import { useCallback, useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import AdminLayout from "../../../layouts/AdminLayout";
import ConfirmDialog from "../../../components/feedback/ConfirmDialog";
import Pagination from "../students/components/Pagination";
import { useToast } from "../students/components/Toast";
import { getAcademicClasses } from "../academic/academic.service";
import { getTeachers } from "../teachers/services/teacher.service";
import { deleteSubject, exportSubjectsCsv, getSubjects, restoreSubject } from "./subject.service";
import type { Subject } from "./subject.types";

const errorMessage = (error: unknown) => (error as { response?: { data?: { message?: string } } }).response?.data?.message || "Request failed";

export default function SubjectListPage() {
  const navigate = useNavigate(); const { showToast } = useToast();
  const [items, setItems] = useState<Subject[]>([]); const [classes, setClasses] = useState<{ id: number; name: string }[]>([]); const [teachers, setTeachers] = useState<{ id: number; fullName: string }[]>([]);
  const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1); const [loading, setLoading] = useState(true); const [deleteId, setDeleteId] = useState<number>();
  const [search, setSearch] = useState(""); const [classId, setClassId] = useState(""); const [teacherId, setTeacherId] = useState(""); const [subjectType, setSubjectType] = useState(""); const [optional, setOptional] = useState(""); const [status, setStatus] = useState(""); const [deleted, setDeleted] = useState(false); const [sort, setSort] = useState("subjectName,asc");
  useEffect(() => { Promise.all([getAcademicClasses(0, 100), getTeachers(1, 100)]).then(([classPage, teacherPage]) => { setClasses(classPage.content); setTeachers(teacherPage.data.map((item) => ({ id: item.id, fullName: `${item.firstName} ${item.lastName}`.trim() }))); }); }, []);
  const filters = useMemo(() => ({ search: search || undefined, classId: classId ? Number(classId) : undefined, teacherId: teacherId ? Number(teacherId) : undefined, subjectType: subjectType || undefined, optional: optional === "" ? undefined : optional === "true", status: status || undefined, deleted, page: page - 1, size: 10, sort }), [search, classId, teacherId, subjectType, optional, status, deleted, page, sort]);
  const load = useCallback(async () => { setLoading(true); try { const response = await getSubjects(filters); setItems(response.content); setTotalPages(Math.max(response.totalPages, 1)); } catch (error) { showToast(errorMessage(error), "error"); } finally { setLoading(false); } }, [filters, showToast]);
  useEffect(() => { queueMicrotask(load); }, [load]);
  const remove = async () => { if (!deleteId) return; try { await deleteSubject(deleteId); setDeleteId(undefined); showToast("Subject deleted successfully", "success"); await load(); } catch (error) { showToast(errorMessage(error), "error"); } };
  const restore = async (id: number) => { try { await restoreSubject(id); showToast("Subject restored successfully", "success"); await load(); } catch (error) { showToast(errorMessage(error), "error"); } };
  const exportCsv = async () => { const blob = await exportSubjectsCsv(filters); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "subjects.csv"; link.click(); URL.revokeObjectURL(url); };
  const filterClass = "h-10 rounded-xl border border-gray-200 px-3 text-sm";
  return <AdminLayout><div className="space-y-5"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div><h1 className="text-2xl md:text-3xl font-bold text-gray-800">Subject Management</h1><p className="text-gray-500">Manage class subjects and teacher assignments</p></div><button onClick={() => navigate("/admin/subjects/add")} className="px-5 py-2.5 bg-[#234A91] text-white rounded-xl">Add Subject</button></div>
    <div className="bg-white rounded-xl p-4 shadow-sm space-y-3"><div className="flex flex-col lg:flex-row gap-3"><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Search code or name" className={`${filterClass} flex-1`} /><button onClick={exportCsv} className="px-4 py-2 border rounded-xl">Export CSV</button><button onClick={() => load()} className="px-4 py-2 border rounded-xl">Refresh</button></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-6 gap-3">
      <select value={classId} onChange={(event) => { setClassId(event.target.value); setPage(1); }} className={filterClass}><option value="">All Classes</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>
      <select value={teacherId} onChange={(event) => { setTeacherId(event.target.value); setPage(1); }} className={filterClass}><option value="">All Teachers</option>{teachers.map((item) => <option key={item.id} value={item.id}>{item.fullName}</option>)}</select>
      <select value={subjectType} onChange={(event) => { setSubjectType(event.target.value); setPage(1); }} className={filterClass}><option value="">All Types</option><option value="THEORY">Theory</option><option value="PRACTICAL">Practical</option><option value="THEORY_PRACTICAL">Theory + Practical</option></select>
      <select value={optional} onChange={(event) => { setOptional(event.target.value); setPage(1); }} className={filterClass}><option value="">Optional / Compulsory</option><option value="false">Compulsory</option><option value="true">Optional</option></select>
      <select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }} className={filterClass}><option value="">All Statuses</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select>
      <label className={`${filterClass} flex items-center gap-2`}><input type="checkbox" checked={deleted} onChange={(event) => { setDeleted(event.target.checked); setPage(1); }} /> Deleted</label>
    </div></div>
    <div className="bg-white rounded-xl shadow-sm overflow-x-auto"><table className="w-full min-w-[1250px] text-sm"><thead className="bg-gray-50"><tr><th className="p-3 text-left">SN</th>{[["subjectCode","Subject Code"],["subjectName","Subject Name"],["className","Class"],["assignedTeacherCount","Teachers"],["subjectType","Type"],["fullMarks","Full Marks"],["passMarks","Pass Marks"],["creditHours","Credit Hours"],["optional","Optional"],["status","Status"]].map(([key,label]) => <th key={key} onClick={() => setSort(`${key},${sort === `${key},asc` ? "desc" : "asc"}`)} className="p-3 text-left cursor-pointer">{label}</th>)}<th className="p-3 text-right">Actions</th></tr></thead><tbody>{loading ? <tr><td colSpan={12} className="p-10 text-center">Loading subjects...</td></tr> : items.map((item, index) => <tr key={item.id} className="border-t"><td className="p-3">{(page - 1) * 10 + index + 1}</td><td className="p-3 font-medium">{item.subjectCode}</td><td className="p-3"><button onClick={() => navigate(`/admin/subjects/${item.id}`)} className="text-[#234A91]">{item.subjectName}</button></td><td className="p-3">{item.className}</td><td className="p-3">{item.assignedTeacherCount}</td><td className="p-3">{item.subjectType.replace("_", " + ")}</td><td className="p-3">{item.fullMarks}</td><td className="p-3">{item.passMarks}</td><td className="p-3">{item.creditHours}</td><td className="p-3">{item.optional ? "Optional" : "Compulsory"}</td><td className="p-3">{item.status}</td><td className="p-3 text-right space-x-3">{item.deleted ? <button onClick={() => restore(item.id)} className="text-green-700">Restore</button> : <><button onClick={() => navigate(`/admin/subjects/${item.id}/edit`)} className="text-[#234A91]">Edit</button><button onClick={() => setDeleteId(item.id)} className="text-red-600">Delete</button></>}</td></tr>)}{!loading && items.length === 0 && <tr><td colSpan={12} className="p-10 text-center text-gray-500">No subjects found</td></tr>}</tbody></table></div>
    <Pagination currentPage={page} totalPages={totalPages} onPageChange={setPage} />
    <ConfirmDialog open={deleteId !== undefined} title="Delete Subject" description="The subject and its active teacher assignments will be soft deleted." confirmLabel="Delete" variant="destructive" onConfirm={remove} onCancel={() => setDeleteId(undefined)} />
  </div></AdminLayout>;
}
