import { useState } from "react";
import { Download, FileSpreadsheet, LoaderCircle } from "lucide-react";
import { useToast } from "../../students/components/Toast";
import type { Lookups } from "../AttendanceWorkspace";
import { errorMessage, exportReport } from "../attendance.service";
import type { AttendanceFilters } from "../attendance.types";
import { cardClass, fieldClass, FilterField, OptionSelect, primaryButton, secondaryButton, today } from "../components/AttendanceUi";

const saveBlob = (blob: Blob, fileName: string) => { const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = fileName; anchor.click(); URL.revokeObjectURL(url); };
export default function ReportsView({ lookups }: { lookups: Lookups }) {
  const { showToast } = useToast(); const month = today().slice(0, 7); const [filters, setFilters] = useState<AttendanceFilters & { reportType: string }>({ reportType: "student-summary", startDate: `${month}-01`, endDate: today() }); const [format, setFormat] = useState<"csv" | "pdf">();
  const download = async (value: "csv" | "pdf") => { setFormat(value); try { const blob = await exportReport(value, filters); saveBlob(blob, `attendance-${filters.reportType}-${filters.startDate}-${filters.endDate}.${value}`); showToast(`${value.toUpperCase()} report downloaded`, "success"); } catch (error) { showToast(errorMessage(error), "error"); } finally { setFormat(undefined); } };
  return <div className="grid grid-cols-1 gap-5 xl:grid-cols-[1fr_340px]"><section className={`${cardClass} p-5`}><h2 className="font-semibold text-gray-900">Generate Attendance Report</h2><p className="mb-5 text-sm text-gray-500">Choose the scope and export a server-generated report.</p><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><FilterField label="Report type"><select className={fieldClass} value={filters.reportType} onChange={(event) => setFilters({ ...filters, reportType: event.target.value })}><option value="student-summary">Student summary</option><option value="student-detailed">Student detailed</option><option value="teacher-summary">Teacher summary</option><option value="absence">Absence report</option><option value="late-arrival">Late arrival report</option></select></FilterField><FilterField label="Academic session"><OptionSelect value={filters.academicSessionId} onChange={(academicSessionId) => setFilters({ ...filters, academicSessionId })} options={lookups.sessions} placeholder="All sessions"/></FilterField><FilterField label="Start date"><input type="date" className={fieldClass} value={filters.startDate} onChange={(event) => setFilters({ ...filters, startDate: event.target.value })}/></FilterField><FilterField label="End date"><input type="date" className={fieldClass} value={filters.endDate} onChange={(event) => setFilters({ ...filters, endDate: event.target.value })}/></FilterField><FilterField label="Class"><OptionSelect value={filters.classId} onChange={(classId) => setFilters({ ...filters, classId, sectionId: undefined })} options={lookups.classes} placeholder="All classes"/></FilterField><FilterField label="Section"><OptionSelect value={filters.sectionId} onChange={(sectionId) => setFilters({ ...filters, sectionId })} options={lookups.sections.filter((item) => !filters.classId || !item.classId || item.classId === filters.classId)} placeholder="All sections"/></FilterField></div><div className="mt-6 flex flex-wrap gap-3"><button className={primaryButton} disabled={Boolean(format)} onClick={() => download("csv")}>{format === "csv" ? <LoaderCircle size={17} className="animate-spin"/> : <FileSpreadsheet size={17}/>}Download CSV</button><button className={secondaryButton} disabled={Boolean(format)} onClick={() => download("pdf")}>{format === "pdf" ? <LoaderCircle size={17} className="animate-spin"/> : <Download size={17}/>}Download PDF</button></div></section><aside className={`${cardClass} p-5`}><h2 className="font-semibold">Report Contents</h2><ul className="mt-4 space-y-3 text-sm text-gray-600"><li>Attendance totals by selected scope</li><li>Present, absent, late, and leave breakdown</li><li>Attendance percentage and working days</li><li>Applied academic, class, and date filters</li></ul><div className="mt-5 rounded-lg bg-blue-50 p-4 text-sm text-blue-800">Large reports may take a few moments to prepare. Keep this page open until the download starts.</div></aside></div>;
}
