import type { DashboardData } from "../types/dashboard";

export const getAdminDashboard = async (): Promise<DashboardData> => {
  return {
    schoolName: "ABC Secondary School",
    statistics: {
      totalStudents: 1240,
      totalTeachers: 85,
      totalParents: 1240,
      totalClasses: 42,
      attendanceToday: 1185,
      feeCollectionThisMonth: 850000,
      pendingFees: 125000,
      upcomingExams: 5,
      upcomingEvents: 8,
    },
    attendance: {
      present: 1185,
      absent: 32,
      late: 15,
      leave: 6,
      halfDay: 2,
      total: 1240,
      trend: [
        { day: "Mon", present: 1150, absent: 28 },
        { day: "Tue", present: 1165, absent: 25 },
        { day: "Wed", present: 1170, absent: 22 },
        { day: "Thu", present: 1155, absent: 30 },
        { day: "Fri", present: 1140, absent: 35 },
        { day: "Sat", present: 1185, absent: 32 },
        { day: "Sun", present: 0, absent: 0 },
      ],
    },
    revenue: {
      monthlyFeeCollection: 1200000,
      pendingCollection: 125000,
      collectedAmount: 850000,
      monthlyData: [
        { month: "Jan", amount: 800000 },
        { month: "Feb", amount: 850000 },
        { month: "Mar", amount: 900000 },
        { month: "Apr", amount: 750000 },
        { month: "May", amount: 950000 },
        { month: "Jun", amount: 850000 },
      ],
    },
    notices: [
      {
        id: 1,
        title: "Annual Sports Day",
        content: "Annual sports day will be held on 25th July.",
        date: "2026-07-10",
        pinned: true,
        unread: true,
      },
      {
        id: 2,
        title: "Mid-term Exam Schedule",
        content: "Mid-term exams start from 15th August.",
        date: "2026-07-08",
        pinned: true,
        unread: true,
      },
      {
        id: 3,
        title: "Parent-Teacher Meeting",
        content: "PTM scheduled for 20th July.",
        date: "2026-07-05",
        pinned: false,
        unread: false,
      },
      {
        id: 4,
        title: "Holiday Notice",
        content: "School will remain closed on 21st July.",
        date: "2026-07-01",
        pinned: false,
        unread: false,
      },
    ],
    leaves: [
      {
        id: 1,
        name: "Ram Sharma",
        type: "teacher",
        role: "Math Teacher",
        fromDate: "2026-07-15",
        toDate: "2026-07-16",
        reason: "Family function",
        status: "pending",
      },
      {
        id: 2,
        name: "Sita Gurung",
        type: "teacher",
        role: "English Teacher",
        fromDate: "2026-07-18",
        toDate: "2026-07-19",
        reason: "Medical leave",
        status: "pending",
      },
      {
        id: 3,
        name: "Aarav Khadka",
        type: "student",
        role: "Grade 10",
        fromDate: "2026-07-14",
        toDate: "2026-07-14",
        reason: "Fever",
        status: "pending",
      },
    ],
    calendar: [
      { id: 1, title: "Sports Day", date: "2026-07-25", type: "event" },
      { id: 2, title: "Mid-term Exam", date: "2026-08-15", type: "exam" },
      { id: 3, title: "PTM", date: "2026-07-20", type: "meeting" },
      { id: 4, title: "Independence Day", date: "2026-08-15", type: "holiday" },
      { id: 5, title: "Science Fair", date: "2026-08-05", type: "event" },
    ],
    events: [
      {
        id: 1,
        title: "Annual Sports Day",
        date: "2026-07-25",
        type: "school",
      },
      {
        id: 2,
        title: "Mid-term Exams Start",
        date: "2026-08-15",
        type: "exam",
      },
      {
        id: 3,
        title: "Staff Meeting",
        date: "2026-07-18",
        type: "meeting",
      },
      {
        id: 4,
        title: "New Admission Open",
        date: "2026-07-01",
        type: "announcement",
      },
    ],
    topStudents: [
      {
        id: 1,
        name: "Aarav Khadka",
        marks: 98,
        class: "Grade 10-A",
      },
      {
        id: 2,
        name: "Sita Gurung",
        marks: 96,
        class: "Grade 9-B",
      },
      {
        id: 3,
        name: "Ram Sharma",
        marks: 95,
        class: "Grade 10-A",
      },
      {
        id: 4,
        name: "Maya Tamang",
        marks: 94,
        class: "Grade 8-C",
      },
      {
        id: 5,
        name: "Kiran Thapa",
        marks: 93,
        class: "Grade 9-A",
      },
    ],
    topTeachers: [
      {
        id: 1,
        name: "John Doe",
        subject: "Mathematics",
        performance: 98,
      },
      {
        id: 2,
        name: "Jane Smith",
        subject: "English",
        performance: 96,
      },
      {
        id: 3,
        name: "Robert Brown",
        subject: "Science",
        performance: 94,
      },
      {
        id: 4,
        name: "Emily Davis",
        subject: "Social Studies",
        performance: 92,
      },
    ],
    recentActivities: [
      {
        id: 1,
        action: "Student Added",
        description: "New student Aarav Khadka enrolled in Grade 10-A",
        time: "2 hours ago",
      },
      {
        id: 2,
        action: "Teacher Added",
        description: "New teacher Ram Sharma joined Mathematics dept",
        time: "5 hours ago",
      },
      {
        id: 3,
        action: "Attendance Marked",
        description: "Attendance marked for Grade 10-A",
        time: "6 hours ago",
      },
      {
        id: 4,
        action: "Exam Created",
        description: "Mid-term exam schedule published",
        time: "1 day ago",
      },
      {
        id: 5,
        action: "Fee Received",
        description: "Fee received from 25 students today",
        time: "1 day ago",
      },
      {
        id: 6,
        action: "Notice Published",
        description: "Annual Sports Day notice published",
        time: "2 days ago",
      },
    ],
    admissions: [
      {
        id: 1,
        name: "Aarav Khadka",
        class: "Grade 10",
        date: "2026-07-10",
        status: "Confirmed",
      },
      {
        id: 2,
        name: "Sita Gurung",
        class: "Grade 9",
        date: "2026-07-09",
        status: "Pending",
      },
      {
        id: 3,
        name: "Ram Sharma",
        class: "Grade 8",
        date: "2026-07-08",
        status: "Confirmed",
      },
      {
        id: 4,
        name: "Maya Tamang",
        class: "Grade 7",
        date: "2026-07-07",
        status: "Confirmed",
      },
      {
        id: 5,
        name: "Kiran Thapa",
        class: "Grade 10",
        date: "2026-07-06",
        status: "Pending",
      },
    ],
    userOverview: {
      students: 1240,
      teachers: 85,
      parents: 1240,
      staff: 25,
    },
    birthdayStudents: [
      {
        id: 1,
        name: "Aarav Khadka",
        class: "Grade 10-A",
        date: "2026-07-15",
      },
      {
        id: 2,
        name: "Sita Gurung",
        class: "Grade 9-B",
        date: "2026-07-16",
      },
      {
        id: 3,
        name: "Ram Sharma",
        class: "Grade 8-A",
        date: "2026-07-18",
      },
    ],
    upcomingFeeDues: [
      {
        id: 1,
        studentName: "Aarav Khadka",
        class: "Grade 10-A",
        amount: 15000,
        dueDate: "2026-07-20",
        status: "pending",
      },
      {
        id: 2,
        studentName: "Sita Gurung",
        class: "Grade 9-B",
        amount: 12000,
        dueDate: "2026-07-18",
        status: "overdue",
      },
      {
        id: 3,
        studentName: "Ram Sharma",
        class: "Grade 8-A",
        amount: 10000,
        dueDate: "2026-07-22",
        status: "pending",
      },
    ],
    recentNotifications: [
      {
        id: 1,
        title: "Fee Reminder",
        message: "Fee payment deadline is approaching for Grade 10.",
        time: "1 hour ago",
      },
      {
        id: 2,
        title: "Exam Schedule",
        message: "Mid-term exam schedule has been published.",
        time: "3 hours ago",
      },
      {
        id: 3,
        title: "Staff Meeting",
        message: "Monthly staff meeting scheduled for Friday.",
        time: "5 hours ago",
      },
    ],
  };
};

