ALTER TABLE modules ADD COLUMN IF NOT EXISTS selectable BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE modules ADD COLUMN IF NOT EXISTS coming_soon BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE modules ADD COLUMN IF NOT EXISTS category VARCHAR(30) NULL;
ALTER TABLE modules ADD COLUMN IF NOT EXISTS required BOOLEAN NOT NULL DEFAULT FALSE;
