ALTER TABLE demo_requests ADD COLUMN IF NOT EXISTS logo_key VARCHAR(500);
ALTER TABLE demo_requests ADD COLUMN IF NOT EXISTS provisioned_school_id BIGINT NULL;
ALTER TABLE demo_requests ADD COLUMN IF NOT EXISTS demo_school_id BIGINT NULL;
ALTER TABLE demo_requests ADD COLUMN IF NOT EXISTS accepted_at DATETIME NULL;
ALTER TABLE demo_requests ADD COLUMN IF NOT EXISTS accepted_by BIGINT NULL;
ALTER TABLE demo_requests ADD COLUMN IF NOT EXISTS email_status VARCHAR(20) NOT NULL DEFAULT 'PENDING';
ALTER TABLE demo_requests ADD COLUMN IF NOT EXISTS email_error VARCHAR(500) NULL;
ALTER TABLE demo_requests ADD COLUMN IF NOT EXISTS credentials_sent_at DATETIME NULL;
ALTER TABLE demo_requests ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE demo_schools ADD COLUMN IF NOT EXISTS school_id BIGINT NULL;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS starts_on DATE NULL;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS ends_on DATE NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_demo_requests_provisioned_school ON demo_requests(provisioned_school_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_demo_requests_demo_school ON demo_requests(demo_school_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_demo_schools_school ON demo_schools(school_id);
CREATE INDEX IF NOT EXISTS ix_demo_requests_email_status ON demo_requests(email_status);
ALTER TABLE demo_requests ADD CONSTRAINT fk_demo_requests_school FOREIGN KEY (provisioned_school_id) REFERENCES schools(id);
ALTER TABLE demo_requests ADD CONSTRAINT fk_demo_requests_demo_school FOREIGN KEY (demo_school_id) REFERENCES demo_schools(id);
ALTER TABLE demo_schools ADD CONSTRAINT fk_demo_schools_school FOREIGN KEY (school_id) REFERENCES schools(id);
