CREATE TABLE IF NOT EXISTS demo_conversion_history (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    conversion_code VARCHAR(20) NOT NULL UNIQUE,
    demo_request_id BIGINT NOT NULL,
    demo_school_id BIGINT NOT NULL UNIQUE,
    paid_school_id BIGINT NOT NULL UNIQUE,
    school_name VARCHAR(255) NOT NULL,
    converted_by BIGINT NOT NULL,
    conversion_date DATE NOT NULL,
    initial_subscription_plan VARCHAR(255),
    subscription_duration INT,
    enabled_modules VARCHAR(1000),
    payment_reference VARCHAR(255),
    payment_method VARCHAR(50),
    payment_amount DECIMAL(12,2),
    currency VARCHAR(3) NOT NULL DEFAULT 'NPR',
    remarks VARCHAR(2000),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    INDEX idx_conversion_history_demo_request (demo_request_id),
    INDEX idx_conversion_history_demo_school (demo_school_id),
    INDEX idx_conversion_history_paid_school (paid_school_id),
    INDEX idx_conversion_history_converted_by (converted_by),
    INDEX idx_conversion_history_conversion_date (conversion_date),
    INDEX idx_conversion_history_code (conversion_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
