import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import AdminLayout from "../../../../layouts/AdminLayout";
import { getTeacherAssignments, getTeacherById, getTeacherLeaves } from "../services/teacher.service";
import type { Teacher } from "../types/teacher.types";

export default function TeacherDetailPage() {
  const { id } = useParams(); const navigate = useNavigate();
  const [teacher, setTeacher] = useState<Teacher>(); const [assignments, setAssignments] = useState<unknown[]>([]); const [leaves, setLeaves] = useState<unknown[]>([]);
  useEffect(() => { const teacherId = Number(id); Promise.all([getTeacherById(teacherId), getTeacherAssignments(teacherId), getTeacherLeaves(teacherId)]).then(([item, assigned, leave]) => { setTeacher(item); setAssignments(assigned); setLeaves(leave); }); }, [id]);
  if (!teacher) return <AdminLayout><div className="p-8">Loading teacher...</div></AdminLayout>;
  const fields = [["Teacher ID", teacher.teacherId], ["Name", teacher.fullName], ["Email", teacher.email], ["Phone", teacher.phone], ["Qualification", teacher.qualification], ["Experience", teacher.experience], ["Department", teacher.department], ["Designation", teacher.designation], ["Employment", teacher.employmentType], ["Status", teacher.status], ["Salary", teacher.basicSalary]];
  return <AdminLayout><div className="space-y-6"><div className="flex flex-col sm:flex-row sm:justify-between gap-3"><div><h1 className="text-2xl md:text-3xl font-bold text-gray-800">Teacher Profile</h1><p className="text-gray-500">{teacher.fullName}</p></div><button onClick={() => navigate(`/admin/teachers/${teacher.id}/edit`)} className="px-5 py-2 rounded-xl bg-[#234A91] text-white">Edit Teacher</button></div><div className="grid grid-cols-1 md:grid-cols-3 gap-4">{fields.map(([label, value]) => <div key={String(label)} className="bg-white p-4 rounded-xl shadow-sm"><p className="text-xs uppercase text-gray-500">{label}</p><p className="mt-1 font-medium text-gray-800">{String(value || "-")}</p></div>)}</div><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><div className="bg-white p-5 rounded-xl"><h2 className="font-semibold">Class & Subject Assignments</h2><p className="text-3xl mt-3">{assignments.length}</p></div><div className="bg-white p-5 rounded-xl"><h2 className="font-semibold">Leave Summary</h2><p className="text-3xl mt-3">{leaves.length}</p></div><div className="bg-white p-5 rounded-xl"><h2 className="font-semibold">Attendance Summary</h2><p className="text-sm mt-3 text-gray-500">No teacher attendance records</p></div></div><div className="bg-white p-5 rounded-xl"><h2 className="font-semibold mb-3">Activity Timeline</h2><p className="text-sm text-gray-600">Teacher record created and last updated through Teacher Management.</p></div></div></AdminLayout>;
}
