package com.pathshala.entity;

public enum ModuleCode {
    STUDENT_MANAGEMENT,
    STUDENT_DASHBOARD,
    TEACHER_MANAGEMENT,
    TEACHER_DASHBOARD,
    SUBJECT_MANAGEMENT,
    TEACHER_ASSIGNMENT,
    PARENT_MANAGEMENT,
    PARENT_DASHBOARD,
    ATTENDANCE,
    EXAMINATION,
    ASSIGNMENT,
    FEE_MANAGEMENT,
    LEAVE_MANAGEMENT,
    NOTIFICATIONS,
    ANALYTICS_DASHBOARD,
    ACCOUNTS,
    LIBRARY,
    TRANSPORT,
    HOSTEL,
    INVENTORY,
    PAYROLL,
    HR_MANAGEMENT,
    ACADEMIC_CALENDAR,
    TIMETABLE,
    CERTIFICATES
}
